### ISSUE TITLE
Transaction failure: Invalid JSON RPC response on outbound crypto tranactions.

### ISSUE THREAD

**Issue by V2user** [unigrid-project/janus-cypherium#1]
This issue tracker is only for technical issues related to Janus.
General Janus questions and/or support requests and are best directed to [Discord](https://discord.gg/CRWZ7V5).

### Describe the issue
Attempted to send cryptocurrency out of wallet but error showed - Transaction failure: Invalid JSON RPC response which is stopping me from completing the action.

#### If so, please list the steps to reproduce below:
1. Input address to send cryptocurrency to
2. unlocked wallet
3. attempted to send cryptocurrency out of wallet but error showed - Transaction failure: Invalid JSON RPC response

### Expected behavior
The cryptocurrency should have been sent from the wallet to the new address.

### Actual behavior
The error code (above) showed and movement was stopped.

### Screenshots.
![image](https://user-images.githubusercontent.com/105197767/167362601-bb894356-e86e-497c-8743-98cee055ffac.png)

### What version of Janus are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.
- Janus-Cypherium-0.2.3

### Machine specs:
- OS: 19043.1645
- CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
- RAM: 16.0 GB
- Disk size: 371 GB
- Disk Type (HD/SDD): SDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a paste bin type site are preferred.

**Comment by DazShaw** [comment]
I've just got the exact same issue. Any help would be appreciated! Thanks

**Comment by samanees** [comment]
I am having the same problem, what is the solution please

**Comment by NetZeroEarthCO2** [comment]
Was their a resolution to this? I would like to know as well

**Comment by DazShaw** [comment]
No solution yet

**Comment by ghost** [comment]
Are our coins stuck in this wallet?  
I am getting the same error months after the issue was reported

**Comment by ghost** [comment]
"The Janus unigrid wallet is not up to date.
We remove it out our messages also.
Better use mobile.
You can use the seeds from the janus wallet to import in the mobile one."

This is a message from the discord.  I used the Janus seeds I now have them in a functioning iOs wallet.

**Comment by dekm** [comment]
We've asked the Cypherium team what changed so we can fix it. They have not replied so unfortunately there is not much we can do to resolve this issue until they reply.

**Comment by DazShaw** [comment]
Solution for Android: 
I followed the link below to download the cypherium wallet apk for android onto my phone. 
When installed and opened, I copied my wallet's private key and password to the app. I can access my cypherium wallet on my phone now and tested a transfer to MEXC exchange. 
The transfer requires 8 Network Confirmations and is taking a very vey long time, but I can see it processing in my exchange wallet

### https://github.com/cypherium/Cypherium-Wallet/blob/master/CPH.apk

**Comment by samanees** [comment]
The only solution that I found was to use a Apple device

**Comment by dekm** [comment]
Closing this issue as there is not anything we can do on our end to resolve it. As others have mentioned, please use their mobile wallets.
